#!/bin/bash
#SBATCH --job-name=nnunet_hard_samples_mining
#SBATCH --partition=bme_cpu
#SBATCH --cpus-per-task=4
#SBATCH --output=./job_loglog/%jout_cpu.out
#SBATCH --error=./job_loglog/%jerr_cpu.out
#SBATCH -N 1   
#SBATCH --mem 20G
#SBATCH -t 24:00:00


echo ${SLURM_JOB_NODELIST}$
echo start on $(data)

# python get_nnunet_hard_sample2csv_training_data.py
python /public_bme/data/xiongjl/inference_result/myself/confirm.py

echo end on $(data) 