# Config file for AttnFPN-def-DETR

# General training
experiment_name: ...
device: cuda
val_interval: 1
seed: 1
num_classes : 1
save_frequence: 5
# mode
debug_mode: False # use the 200 data training, 50 data validation, testing
train_overfit: False # use one data trianing, validation, testing
best_loss: 3000.

train_overfit_path: ...
epochs: 30
lr: 1e-3

save_for_see: True

# Scheduler
scheduler_steps: 35
gamma: 0.1
clip_max_norm: 1000

# Data
bbox_padding: 1
patch_size: [128, 128, 128]
# patch_size: [224, 224, 224]  / [160, 160, 160] / [128, 128, 128]
use_center_or_randomly_rate:  0.4 # 0.5
data_type: no_masked
data_number: all  # all or not all

# GT path file name
masked_200_training_gt: ...
masked_50_testing_gt: ...
whole_200_training_gt: ...
whole_50_testing_gt: ...
overfit_1_training_gt: ...

freeze: False
cascade:
  cascade: False
  eval: False
  confi: 0.6
  stage_one_model_path: ...
  stage_two_model_path: ...
cascade_hmap_threshold: 0.3 # 这个时候最好修改一下这个lr，让之小一点

centernet_point: False
resume: ...
model_name: ...
channels: 1
# Path
root_path : ...
lymph_nodes_data_path: ...
csv_names_root_path: ...
image_npy_path: ...
log_path: ...
image_save_path: ...

# Dataloader
batch_size: 1
batch_size_true: 4
shuffle: True
num_workers: 0

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2

# Losses
pos_neg_threshold: 0.99
pos_loss_weight_int: 1.
loss_coefs:  # Detection
  origin_hmap: 0.
  weight_mse_loss: 0.
  mse: 1.
  offset: 1. 
  seg_loss: 0. 
  regression_hmap: 0. 
  whd: 0.1
  pos_weight: 2. 
  neg_weight: 1.

point_weight: 4

# evaluator
evaluator_threshold: 50
overlap: [15, 15, 15]
confidence: 0.05
test_training_mode_name_path: ...
test_testing_mode_name_path: ...
test_mode_name_path: ...
iou_confi: 0.01
ap_confi: 0.35

# decode_bbox
decode_box_kernel_size: 9
nms_threshold: 0.1